version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    container_name: prisma
    restart: unless-stopped
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          mongodb:
            connector: mongo
            uri: mongodb://xluos:xluos@mongo
          postgres:
            connector: postgres
            host: postgres
            port: 5432
            user: xluos
            password: xluos
            migrations: true
    networks:
      - default
      - app_net
networks: 
  app_net:
    external: true

