version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.24
    container_name: prisma
    restart: unless-stopped
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://xluos:xluos@mongo
    networks:
      - default
      - app_net
networks: 
  app_net:
    external: true

