version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgresql
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
          default:
          app_net:
              aliases:
                - postgres
networks: 
  app_net:
    external: true
volumes:
  postgres: