version: '3'

services:

  mongo:
    image: mongo:3.6
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo/db:/data/db
    networks: 
      default:
      app_net:
          aliases:
            - mongo
networks: 
  app_net:
    external: true

